### ISSUE TITLE
[DOC] Add documentation on how EOReader can improve your data handling

### ISSUE THREAD

**Issue by remi-braun** [sertit/eoreader#108]
- [ ] Simplifies the handling of Sentinel-2 data (takes into account all the existing processing baselines) #11 #34 
- [ ] Solves the handling of multiswath COSMO data by SNAP #78 
- [ ] Geocoding of Sentinel-3 data #55 
- [ ] Handling of planet multi-tile products #45 
- [ ] ...
