### ISSUE TITLE
OPTIM: Speeding up EOReader

### ISSUE THREAD

**Issue by remi-braun** [sertit/eoreader#58]
It could be really useful to use external libraries to speed up EOReader and ensure the clusterization works properly:
- [ ] Optimize the code using libraries such as [numba](https://numba.pydata.org/), [xarray-geospatial](https://xarray-spatial.org/)...
- [ ] Make Dask really work (even if #4 is closed) 
   - Ensure reading and writing is accelerated
   - Check if reprojection, geocoding, index computation can be daskified and/or optimized (Spyndex #47, geocode S3 #55, [reprojection](https://github.com/corteva/rioxarray/issues/119))
- [ ] Enforce the window reading (#25)
- [ ] Don't use SNAP for SAR data (#2)

**Comment by remi-braun** [comment]
WarpedVRT optimization has been implemented in 9aaf672a28b9c9761c87a844d53fbee069ecf300
